---
version: '2.3'

services:

  dvwa_web:
    image: cytopia/dvwa:php-${PHP_VERSION:-7.2}
    container_name: dvwa_web
    ports:
      - "${LISTEN_PORT:-8000}:80"
    networks:
      - dvwa-net
    cpus: "0.1"
    mem_limit: 128m
    memswap_limit: 256m
    oom_kill_disable: true
    environment:
      - RECAPTCHA_PRIV_KEY=${RECAPTCHA_PRIV_KEY:-}
      - RECAPTCHA_PUB_KEY=${RECAPTCHA_PUB_KEY:-}
      - SECURITY_LEVEL=${SECURITY_LEVEL:-medium}
      - PHPIDS_ENABLED=${PHPIDS_ENABLED:-0}
      - PHPIDS_VERBOSE=${PHPIDS_VERBOSE:-0}
      - PHP_DISPLAY_ERRORS=${PHP_DISPLAY_ERRORS:-0}
      - MYSQL_HOSTNAME=dvwa_db
      - MYSQL_DATABASE=dvwa
      - MYSQL_USERNAME=dvwa
      - MYSQL_PASSWORD=p@ssw0rd

  dvwa_db:
    image: mysql:5.6
    hostname: dvwa_db
    container_name: dvwa_db
    cpus: "0.1"
    mem_limit: 128m
    memswap_limit: 256m
    oom_kill_disable: true
    volumes:
      - dvwa_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: p@ssw0rd
    networks:
      - dvwa-net

networks:
  dvwa-net:
    driver: bridge

volumes:
  dvwa_db_data:
    driver: local

